version: '3'

services:
  app:
    #build: .
    container_name: blog-hugo
    ports:
        - "1313:1313"
    image: yonh/bin-hugo
    #restart: always
    volumes:
        - ./:/opt
    command: hugo server -D --bind="0.0.0.0"
